name: Publish Package to JSR
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"

      - name: Verify code integrity
        run: deno task check-all

      - name: Publish to JSR
        run: deno publish
